global.RAZAS = {
  CRUZA: 'Cruza',
  BEAGLE: 'Beagle',
  BORDER_COLLIE: 'Border Collie',
  BOXER: 'Boxer',
  BULLDOG: 'Bulldog',
  BULLDOG_FRANCES: 'Bulldog Frances',
  CANICHE: 'Caniche',
  CHIHUAHUA: 'Chihuahua',
  GOLDEN_RETRIEVER: 'Golden Retriever',
  LABRADOR: 'Labrador',
  LABRADOR_RETRIEVER: 'Labrador Retriever',
  PASTOR_ALEMAN: 'Pastor Aleman',
  PASTOR_AUSTRALIANO: 'Pastor Australiano',
  PASTOR_BELGA: 'Pastor Belga',
  PASTOR_INGLES: 'Pastor Ingles',
  PITBULL: 'Pitbull',
  PUG: 'Pug',
  ROTTWEILER: 'Rottweiler',
  SALCHICHA: 'Salchicha',
};
global.USER_IDS ={
  LUCIA: 1,
  PEDRO: 2,
  JUANCHO: 3,
  AGUSTIN: 4,
  NAMI: 5,
  AGUSTINA:6,
  CORDELIA: 7,
  MISTY:8,
  LDR:9,
};